[package]
name = "led_bargraph"
version = "0.2.0"
authors = ["Jason Peacock <jason@jasonpeacock.com>"]

[dependencies]
docopt = "1.0.0"
#i2cdev = "0.3.1"
i2cdev = "0.4.0"
#i2cdev = { git = 'https://github.com/rust-embedded/rust-i2cdev' }
num-integer = "0.1.38"
serde = "1.0.66"
serde_derive = "1.0.66"
slog = "2.2.3"
slog-async = "2.3.0"
slog-stdlog = "3.0.2"
slog-term = "2.4.0"
slog-scope = "4.0.1"

